#!/usr/bin/env bash
# =============================================================================
# gen-stream-ports.sh
# =============================================================================
# Generates /etc/nginx/stream-conf.d/gameserver-ports.conf
#
# Port design – TWO distinct ranges to avoid self-loop:
# ┌─────────────────────────────────────────────────────────────────────────┐
# │  EXTERNAL range (TLS-facing, what clients connect to via wss://):       │
# │    EXT_MIN=20000  EXT_MAX=21000                                         │
# │                                                                         │
# │  INTERNAL range (plaintext, where hostNetwork pods actually listen):    │
# │    INT_MIN=30000  INT_MAX=31000  (OFFSET = INT_MIN - EXT_MIN = 10000)   │
# │                                                                         │
# │  Mapping:  nginx listens on EXT_PORT (TLS)                             │
# │            → proxy_pass to 127.0.0.1:(EXT_PORT + OFFSET)               │
# │                                                                         │
# │  Example:  client connects to wss://server.boxgame.shadyggs.xyz:20426  │
# │            nginx terminates TLS on :20426                               │
# │            → forwards plaintext to game-server pod on 127.0.0.1:30426  │
# │                                                                         │
# │  WHY: If nginx binds 0.0.0.0:N and proxy_pass 127.0.0.1:N, nginx owns  │
# │       loopback too, so the connection loops back into itself, causing   │
# │       the SSL_do_handshake error in nginx error.log. Distinct ranges    │
# │       guarantee proxy_pass always reaches the real pod, not nginx.      │
# └─────────────────────────────────────────────────────────────────────────┘
#
# Run on the VM (requires root / sudo):
#   sudo bash scripts/gen-stream-ports.sh
#   sudo nginx -t && sudo systemctl reload nginx
#
# FIREWALL: Open EXT range (clients connect here), NOT the INT range:
#   OCI Security List: TCP 20000-21000 ingress from 0.0.0.0/0
#   OS iptables:       sudo iptables -I INPUT -p tcp --dport 20000:21000 -j ACCEPT
# =============================================================================

set -euo pipefail

EXT_MIN="${EXT_MIN:-20000}"
EXT_MAX="${EXT_MAX:-21000}"
OFFSET=10000   # INT_PORT = EXT_PORT + OFFSET  →  30000-31000
OUT="/etc/nginx/stream-conf.d/gameserver-ports.conf"

echo "Generating stream blocks: external ${EXT_MIN}–${EXT_MAX} → internal $((EXT_MIN+OFFSET))–$((EXT_MAX+OFFSET))"
echo "Output: ${OUT}"

{
  echo "# AUTO-GENERATED by gen-stream-ports.sh – do not edit manually"
  echo "# Re-run the script to regenerate after changing EXT_MIN / EXT_MAX."
  echo "#"
  echo "# Port mapping: listen EXT_PORT (TLS) → proxy_pass 127.0.0.1:(EXT_PORT+${OFFSET})"
  echo "# External (clients) : ${EXT_MIN}–${EXT_MAX}  (open these in OCI Security List)"
  echo "# Internal (pods)    : $((EXT_MIN+OFFSET))–$((EXT_MAX+OFFSET))  (hostNetwork, NOT exposed externally)"
  echo ""
  for ext_port in $(seq "$EXT_MIN" "$EXT_MAX"); do
    int_port=$((ext_port + OFFSET))
    echo "server {"
    echo "    listen ${ext_port} ssl;"
    echo "    proxy_pass 127.0.0.1:${int_port};"
    echo "}"
    echo ""
  done
} | sudo tee "$OUT" > /dev/null

echo "Done. Run: sudo nginx -t && sudo systemctl reload nginx"
